### ISSUE TITLE
能请教你个问题不，如何设置mat-form-field高度啊

### ISSUE THREAD

**Issue by smile2014** [stbui/angular-material-app#29]
能请教你个问题不，如何设置mat-form-field高度啊

**Comment by stbui** [comment]
```scss
mat-form-field {
    height: 100px;
}
```
